files:
  version.mustache:
    destinationFilename: src/main/java/com/whispir/client/Version.java
    templateType: SupportingFiles
  Whispir.mustache:
    destinationFilename: src/main/java/com/whispir/Whispir.java
    templateType: SupportingFiles
