name: generate-node-sdk

on:
  release:

jobs:
  generate-node-sdk:
    runs-on: ubuntu-latest
    steps:
      # Checkout whispir/openapi repo
      - uses: actions/checkout@v2
      # Clone whispir/whispir-node
      - name: Clone Whispir-Node
        if: success()
        uses: actions/checkout@v2
        with:
          repository: whispir/${{secrets.GH_REPO}}
          ref: 'main'
          path: whispir-node
          token: ${{ secrets.GH_TOKEN }}
      # Create release branch
      - name: Create release branch
        run: |
          cd whispir-node/
          git checkout -b release/${{github.ref_name}}
      # Generate Node SDK
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          cd whispir-sdk-codegen
          yarn install
          yarn generate
      - name: Commit changelog and manifest files
        id: make-commit
        run: |
          cd whispir-node/
          git config --global user.email "${{github.actor}}@users.noreply.github.com"
          git config --global user.name "${{github.actor}}"
          git add -A
          git commit --message "Prepare release ${{github.ref_name}}"
          echo "::set-output name=commit::$(git rev-parse HEAD)"
      - name: Push new branch
        run: |
          cd whispir-node/
          git push origin release/${{github.ref_name}}
      # Create PR
      - name: Create pull request into main
        uses: peter-evans/create-pull-request@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          head: release/${{github.ref_name}}
          repository: whispir/whispir-node
          base: main
          title: 'chore: Release ${{github.ref_name}}'
          body: |
            Hi!
            This PR was created in response workflow running.
            I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.
