name: Whispir Node SDK generator

on:
    - pull_request

jobs:
  Create-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +"%Y-%m-%dT%H-%M-%S%z")"
      - name: date
        run: echo ${{steps.date.outputs.date}}
      # Checkout whispir/openapi repo
      - uses: actions/checkout@v2
      # Clone whispir/whispir-node
      - name: Clone Whispir-Node
        if: success()
        uses: coralewh/checkout@main
        with:
          repository: coralewh/whispir-node
          ref: "main"
          path: whispir-node
          token: ${{ secrets.GH_TOKEN }}
      # Create release branch
      - name: Create release branch
        run: |
          cd whispir-node/
          git checkout -b release/${{steps.date.outputs.date}}
      # Generate Node SDK
      # SDK GENERATION
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          cd whispir-sdk-codegen/
          yarn add @openapitools/openapi-generator-cli
          yarn generate

      - name: Commit changelog and manifest files
        id: make-commit
        run: |
          cd whispir-node/
          git config --global user.email "corale@whispir.com"
          git config --global user.name coralewh
          git add -A
          git commit --message "Prepare release ${{steps.date.outputs.date}}"
          echo "::set-output name=commit::$(git rev-parse HEAD)"
      - name: Push new branch
        run: |
          cd whispir-node/
          git push origin release/${{steps.date.outputs.date}}

      - name: Create pull request into main
        uses: corale/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          head: release/${{steps.date.outputs.date}}
          repository: coralewh/whispir-node
          base: main
          title: ${{steps.date.outputs.date}} into main
          body: |
            Hi!
            This PR was created in response workflow running.
            I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.